### ISSUE TITLE
Plan for dark theme?

### ISSUE THREAD

**Issue by 2vg** [danielradosa/cinnamonroll-light#1]
Hi, this theme is very great!
But can u make it for dark theme, in the future?

**Comment by danielradosa** [comment]
It is purposefully light as in Cinnamoroll is white and pastel blue/pink.
However I will consider it. If I do decide to do it, I will write here again.

**Comment by danielradosa** [comment]
@2vg Here is the dark one (will be updating regulary till i figure out best color combination)
[Cinnamoroll DARK](https://marketplace.visualstudio.com/items?itemName=dango.cinnamoroll-dark-theme)
